2.22. Разметка внутренних страниц
htmlacademy-adaptive/1445103-pink-25 pull request #3
Opened 2022-04-07 11:46 UTC by Valeriia-2

2022-04-08 13:25 UTC, feralist21 requested changes
Очень хорошо получилось, молодец! Давай еще чуть чуть поднажмем и сделаем код еще лучше)

2022-04-08 13:25 UTC, feralist21 commented on source/catalog.html
> +          <h1 class="header-title">Фотографии пользователей</h1>
Блок не должен быть внутри его элемента. Подумай, пожалуйста, как здесь можно исправить.

2022-04-08 13:25 UTC, feralist21 commented on source/form.html
> +        <h1 class="header-title">Конкурс на самое безбашенное путешествие с Пинк</h1>
Блок находится внутри его элемента. Не лучшая практика. Пожалуйста, подумай как можно исправить.

2022-04-08 13:25 UTC, feralist21 commented on source/form.html
> +        <h1 class="header-title">Конкурс на самое безбашенное путешествие с Пинк</h1>
Блок находится внутри его элемента. Так не стоит делать. Пожалуйста, подумай как можно исправить.

2022-04-08 13:25 UTC, feralist21 commented on source/form.html
> +          <p class="subtitle">Поделитесь своей историей и получите шанс выиграть ценный приз — 1000 миль на вашу бонусную карту!<span class="subtitle subtitle-additional"> Пожалуйста, заполните форму
Как думаешь, можно ли здесь обойтись одним БЭМ блоком для <p> и сделать <span> его элементом?

2022-04-08 13:25 UTC, feralist21 commented on source/form.html
> +          <p class="subtitle">Поделитесь своей историей и получите шанс выиграть ценный приз — 1000 миль на вашу бонусную карту!<span class="subtitle subtitle-additional"> Пожалуйста, заполните форму
Как думаешь, можно ли здесь обойтись одним БЭМ блоком для <p> и сделать <span> его элементом?

2022-04-08 13:25 UTC, feralist21 commented on source/form.html
> +                  <input class="form-registration__radio visually-hidden" type="radio" id="windows" name="app" value="3">
Рекомендую изменить value у радиокнопок на текстовое описание. Они в любой момент могу поменяться местами и нумерация потеряет актуальность.

2022-04-08 13:25 UTC, feralist21 commented on source/form.html
> +                  <input class="form-registration__radio visually-hidden" type="radio" id="windows" name="app" value="3">
Рекомендую изменить value у радиокнопок на текстовое описание. Они в любой момент могу поменяться местами и нумерация потеряет актульность.

2022-04-08 13:25 UTC, feralist21 commented on source/catalog.html
> +          <h1 class="header-title">Фотографии пользователей</h1>
Аналогичная ситуация как и в файле form.html

2022-04-08 13:25 UTC, feralist21 commented on source/catalog.html
> +          <h1 class="header-title">Фотографии пользователей</h1>
Аналогичная ситуация как и в файле form.html

2022-04-08 13:25 UTC, feralist21 commented on source/catalog.html
> +              <button class="photo__likes-button" type="button"></button>
Обрати внимание на критерий Д18 и сделай этому и похожим элементам текстовое описание.

2022-04-08 13:25 UTC, feralist21 commented on source/catalog.html
> +              <button class="photo__likes-button" type="button"></button>
Обрати внимание на критерий Д18 и сделай этому и похожим элементам текстовое описание.

2022-04-08 13:25 UTC, feralist21 commented on source/catalog.html
> +          <p class="photo-editor__title">Выкладывайте все, что накопилось в телефоне!</p>
Кажется здесь 2 элемента буду излишними. Как думаешь, можно ли упростить их?

2022-04-08 13:25 UTC, feralist21 commented on source/catalog.html
> +          <p class="photo-editor__title">Выкладывайте все, что накопилось в телефоне!</p>
Кажется здесь 2 элемента буду излишними. Как думаешь, можно ли упростить их?

2022-04-08 13:25 UTC, feralist21 commented on source/catalog.html
> +        <div class="photo-iditor__form">
Небольшая опечатка))

2022-04-08 13:25 UTC, feralist21 commented on source/catalog.html
> +        <div class="photo-iditor__form">
Небольшая опечатка))

2022-04-09 01:47 UTC, Valeriia-2 commented on source/catalog.html
> +          <h1 class="header-title">Фотографии пользователей</h1>
Я переделала, но не уверена, что правильно

2022-04-09 03:05 UTC, feralist21 approved these changes
Хорошо получилось, продолжай в том же духе

2022-04-09 03:06 UTC, merged